from __future__ import annotations

from ufpy_esp_synth.config.models import ScenarioName

SCHEMA_BY_SCENARIO: dict[ScenarioName, list[str]] = {
    ScenarioName.PUMP_ONLY: [
        "value_date",
        "esp_id",
        "run_id",
        "is_running",
        "control_label",
        "control_reason",
        "stage_num",
        "pump_freq_hz",
        "p_int_atma",
        "t_int_c",
        # PVT inputs used by ufpy calculations
        "gamma_g",
        "gamma_o",
        "gamma_w",
        "rsb_m3m3",
        "rp_m3m3",
        "pb_atma",
        "t_res_c",
        "bob_m3m3",
        "muob_cp",
        "fw_fr",
        "q_gas_free_sm3day",
        # time-varying feed
        "q_liq_sm3day",
        # PVT computed at intake (used for viscosity correction)
        "mu_mix_cst",
        "gas_fraction_d",
        "q_mix_rc_m3day",
        # pump curve outputs
        "head_m",
        "power_w",
        "eff_d",
    ],
    ScenarioName.PUMP_DP: [
        "value_date",
        "esp_id",
        "run_id",
        "is_running",
        "control_label",
        "control_reason",
        "stage_num",
        "pump_freq_hz",
        "p_int_atma",
        "t_int_c",
        # PVT inputs
        "gamma_g",
        "gamma_o",
        "gamma_w",
        "rsb_m3m3",
        "rp_m3m3",
        "pb_atma",
        "t_res_c",
        "bob_m3m3",
        "muob_cp",
        "fw_fr",
        "q_gas_free_sm3day",
        # time-varying feed
        "q_liq_sm3day",
        # PVT computed at intake
        "mu_mix_cst",
        "gas_fraction_d",
        "q_mix_rc_m3day",
        # pump dp outputs
        "p_dis_atma",
        "t_dis_c",
        "head_m",
        "eff_esp_d",
        "power_fluid_w",
        "power_esp_w",
    ],
    ScenarioName.ESP_SYSTEM: [
        "value_date",
        "esp_id",
        "run_id",
        "is_running",
        "control_label",
        "control_reason",
        "stage_num",
        "pump_freq_hz",
        "p_int_atma",
        "t_int_c",
        # PVT inputs
        "gamma_g",
        "gamma_o",
        "gamma_w",
        "rsb_m3m3",
        "rp_m3m3",
        "pb_atma",
        "t_res_c",
        "bob_m3m3",
        "muob_cp",
        "fw_fr",
        "q_gas_free_sm3day",
        # time-varying feed
        "q_liq_sm3day",
        # PVT computed at intake
        "mu_mix_cst",
        "gas_fraction_d",
        "q_mix_rc_m3day",
        # system / pump outputs
        "p_dis_atma",
        "t_dis_c",
        "head_m",
        "eff_esp_d",
        "power_fluid_w",
        "power_esp_w",
        "system_eff_d",
        # motor inputs (nominals) and surface conditions
        "u_surf_v",
        "motor_u_nom_lin_v",
        "motor_p_nom_kw",
        "motor_f_nom_hz",
        "motor_eff_nom_fr",
        "motor_cosphi_nom_fr",
        "motor_slip_nom_fr",
        "motor_id",
        # motor outputs
        "motor_u_lin_v",
        "motor_i_lin_a",
        "motor_cosphi",
        "motor_slip",
        "motor_eff_d",
        "motor_p_shaft_kw",
        "motor_p_electr_kw",
        "motor_power_cs_kw",
        "motor_eff_full_d",
        "motor_load_d",
        "motor_speed_rpm",
    ],
    ScenarioName.WELL_ESP_SYSTEM: [
        "value_date",
        "esp_id",
        "run_id",
        "is_running",
        "control_label",
        "control_reason",
        "ipr_mode",
        "stage_num",
        "pump_freq_hz",
        "p_wf_atma",
        "drawdown_atma",
        "p_int_atma",
        "p_dis_atma",
        "p_buf_atma",
        "p_wh_target_atma",
        "wellhead_target_error_atma",
        "well_solver_ok",
        "p_cas_atma",
        "p_res_atma",
        "productivity_index",
        "j_calc_sm3day_atma",
        "q_test_sm3day",
        "q_ipr_sm3day",
        "p_test_atma",
        "t_wf_c",
        "t_int_c",
        "t_dis_c",
        "t_buf_c",
        "t_surface_c",
        "h_perf_m",
        "h_esp_m",
        "d_tub_mm",
        "d_cas_mm",
        "gamma_g",
        "gamma_o",
        "gamma_w",
        "rsb_m3m3",
        "rp_m3m3",
        "pb_atma",
        "t_res_c",
        "bob_m3m3",
        "muob_cp",
        "fw_fr",
        "q_gas_free_sm3day",
        "q_liq_sm3day",
        "mu_mix_cst",
        "gas_fraction_d",
        "q_mix_rc_m3day",
        "ksep_total_d",
        "gas_fraction_pump_d",
        "head_m",
        "eff_esp_d",
        "power_fluid_w",
        "power_esp_w",
        "system_eff_d",
        "u_surf_v",
        "motor_u_nom_lin_v",
        "motor_p_nom_kw",
        "motor_f_nom_hz",
        "motor_eff_nom_fr",
        "motor_cosphi_nom_fr",
        "motor_slip_nom_fr",
        "motor_id",
        "motor_u_lin_v",
        "motor_i_lin_a",
        "motor_cosphi",
        "motor_slip",
        "motor_eff_d",
        "motor_p_shaft_kw",
        "motor_p_electr_kw",
        "motor_power_cs_kw",
        "motor_eff_full_d",
        "motor_load_d",
        "motor_speed_rpm",
    ],
}


def columns_for(scenario: ScenarioName) -> list[str]:
    return list(SCHEMA_BY_SCENARIO[scenario])
